baseURL = 'https://austinchristiansen.com'
languageCode = 'en-us'
title = 'Austin Christiansen'
theme = 'digitalgarden'
[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 2
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 2
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/austin-mc'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://linkedin.com/in/austin-christiansen'
  weight = 2
[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/amchristiansen'
  weight = 3